"""
Генератор конфигурационных файлов Asterisk из БД
"""
import subprocess
from pathlib import Path
from typing import List, Optional
from loguru import logger
from sqlalchemy.orm import Session

from ..models.company import Company
from ..models.sip_trunk import SIPTrunk
from ..models.phone_number import PhoneNumber
from ..models.user import User
from ..config import get_settings

settings = get_settings()


class AsteriskConfigGenerator:
    """Генерирует конфигурационные файлы Asterisk из БД"""
    
    def __init__(self, config_path: str = "/etc/asterisk/dynamic"):
        self.config_path = Path(config_path)
        self.pjsip_config_file = self.config_path / "pjsip_dynamic.conf"
        self.extensions_config_file = self.config_path / "extensions_dynamic.conf"
    
    def generate_all_configs(self, db: Session) -> dict:
        """
        Генерирует все конфигурационные файлы
        
        Returns:
            dict: Статус генерации с информацией о созданных файлах
        """
        try:
            # Получаем данные из БД
            companies = db.query(Company).filter(Company.is_active == True).all()
            users = db.query(User).filter(User.is_active == True).all()
            trunks = db.query(SIPTrunk).filter(SIPTrunk.enabled == True).all()
            phone_numbers = db.query(PhoneNumber).filter(PhoneNumber.is_available == True).all()
            
            # Генерируем конфиги
            # ВАЖНО: SIP транки настраиваются вручную в pjsip_mango.conf, генерируем только WebRTC операторов
            pjsip_content = self._generate_pjsip_config(companies, users, [], phone_numbers)  # Передаем пустой список транков
            extensions_content = self._generate_extensions_config(companies, users, trunks, phone_numbers)
            
            # Сохраняем файлы
            self._save_config(self.pjsip_config_file, pjsip_content)
            self._save_config(self.extensions_config_file, extensions_content)
            
            logger.info(f"✅ Конфигурационные файлы сгенерированы")
            logger.info(f"   - {self.pjsip_config_file}")
            logger.info(f"   - {self.extensions_config_file}")
            
            return {
                "status": "success",
                "files": [
                    str(self.pjsip_config_file),
                    str(self.extensions_config_file)
                ],
                "stats": {
                    "companies": len(companies),
                    "users": len(users),
                    "trunks": len(trunks),
                    "phone_numbers": len(phone_numbers)
                }
            }
            
        except Exception as e:
            logger.error(f"❌ Ошибка генерации конфигов: {e}")
            raise
    
    def _generate_pjsip_config(
        self, 
        companies: List[Company], 
        users: List[User], 
        trunks: List[SIPTrunk],
        phone_numbers: List[PhoneNumber]
    ) -> str:
        """Генерирует pjsip.conf"""
        
        lines = [
            ";",
            "; PJSIP Configuration - Auto-generated from Database",
            "; DO NOT EDIT MANUALLY - Changes will be overwritten",
            ";",
            "; Generated by AI Call Agent",
            ";",
            ""
        ]
        
        # Генерируем конфигурацию для каждого пользователя (WebRTC endpoints)
        lines.append("; ========================================")
        lines.append("; WebRTC Operators")
        lines.append("; ========================================")
        lines.append("")
        
        for user in users:
            if not user.sip_username:
                continue
                
            company = next((c for c in companies if c.id == user.company_id), None)
            if not company:
                continue
            
            # Endpoint
            lines.extend([
                f"[{user.sip_username}]",
                "type=endpoint",
                f"context=company_{company.id}",
                "disallow=all",
                "allow=opus",
                "allow=ulaw",
                "webrtc=yes",
                "transport=transport-ws",
                f"auth={user.sip_username}-auth",
                f"aors={user.sip_username}",
                "direct_media=no",
                "ice_support=yes",
                "media_encryption=dtls",
                "dtls_verify=fingerprint",
                "dtls_auto_generate_cert=yes",
                "dtls_setup=actpass",
                "dtls_rekey=0",
                "rtcp_mux=yes",
                "use_avpf=yes",
                "force_avp=no",
                "rtp_symmetric=yes",
                "force_rport=yes",
                "rewrite_contact=yes",
                ""
            ])
            
            # Auth
            lines.extend([
                f"[{user.sip_username}-auth]",
                "type=auth",
                "auth_type=userpass",
                f"username={user.sip_username}",
                f"password={user.sip_password}",
                "realm=asterisk",
                ""
            ])
            
            # AOR
            lines.extend([
                f"[{user.sip_username}]",
                "type=aor",
                "max_contacts=5",
                "remove_existing=yes",
                "",
                ""
            ])
        
        # Генерируем конфигурацию для SIP транков
        lines.append("; ========================================")
        lines.append("; SIP Trunks")
        lines.append("; ========================================")
        lines.append("")
        
        for trunk in trunks:
            company = next((c for c in companies if c.id == trunk.company_id), None)
            if not company:
                continue
            
            trunk_name = f"trunk_{trunk.id}_{trunk.provider}"
            
            # Registration
            lines.extend([
                f"[{trunk_name}-reg]",
                "type=registration",
                f"server_uri={trunk.server_uri}",
                f"client_uri={trunk.client_uri}",
                f"contact_user={trunk.username}",
                f"outbound_auth={trunk_name}-auth",
                "retry_interval=60",
                "forbidden_retry_interval=600",
                "max_retries=10",
                "auth_rejection_permanent=yes",
                f"line=yes",
                f"endpoint={trunk_name}",
                ""
            ])
            
            # Auth
            lines.extend([
                f"[{trunk_name}-auth]",
                "type=auth",
                "auth_type=userpass",
                f"username={trunk.username}",
                f"password={trunk.password}",
                f"realm={trunk.realm}",
                ""
            ])
            
            # Endpoint
            lines.extend([
                f"[{trunk_name}]",
                "type=endpoint",
                f"context=from_trunk_{trunk.id}",
                "disallow=all",
                "allow=ulaw",
                "allow=alaw",
                "allow=opus",
                "transport=transport-udp",
                f"outbound_auth={trunk_name}-auth",
                f"aors={trunk_name}",
                "from_user=${CALLERID(num)}",
                "rtp_symmetric=yes",
                "force_rport=yes",
                "rewrite_contact=yes",
                "send_rpid=yes",
                "direct_media=no",
                ""
            ])
            
            # AOR
            lines.extend([
                f"[{trunk_name}]",
                "type=aor",
                f"contact={trunk.server_uri}",
                "qualify_frequency=60",
                ""
            ])
            
            # Identify (для входящих звонков)
            if trunk.realm:
                lines.extend([
                    f"[{trunk_name}-identify]",
                    "type=identify",
                    f"endpoint={trunk_name}",
                    f"match={trunk.realm}",
                    "",
                    ""
                ])
        
        return "\n".join(lines)
    
    def _generate_extensions_config(
        self, 
        companies: List[Company], 
        users: List[User], 
        trunks: List[SIPTrunk],
        phone_numbers: List[PhoneNumber]
    ) -> str:
        """Генерирует extensions.conf (dialplan)"""
        
        lines = [
            ";",
            "; Dialplan - Auto-generated from Database",
            "; DO NOT EDIT MANUALLY - Changes will be overwritten",
            ";",
            "; Generated by AI Call Agent",
            ";",
            ""
        ]
        
        # Контекст для каждой компании
        for company in companies:
            company_users = [u for u in users if u.company_id == company.id]
            company_trunks = [t for t in trunks if t.company_id == company.id]
            
            if not company_users:
                continue
            
            lines.append(f"; ========================================")
            lines.append(f"; Company: {company.name} (ID: {company.id})")
            lines.append(f"; ========================================")
            lines.append("")
            
            # Внутренний контекст компании
            lines.append(f"[company_{company.id}]")
            
            # Тестовые номера
            lines.extend([
                "; Тестовые номера",
                "exten => 100,1,Answer()",
                "same => n,Playback(demo-echotest)",
                "same => n,Echo()",
                "same => n,Hangup()",
                "",
                "exten => 101,1,Answer()",
                "same => n,SayDigits(${EPOCH})",
                "same => n,Hangup()",
                "",
            ])
            
            # Звонки между операторами внутри компании
            lines.append("; Внутренние звонки между операторами")
            for user in company_users:
                if user.sip_username:
                    lines.extend([
                        f"exten => {user.sip_username},1,NoOp(Звонок на {user.full_name})",
                        f"same => n,Dial(PJSIP/{user.sip_username},60,tT)",
                        "same => n,Hangup()",
                        ""
                    ])
            
            # Исходящие звонки через транк
            if company_trunks:
                trunk = company_trunks[0]  # Используем первый доступный транк
                # Используем статический транк mango-trunk для Mango Office
                trunk_name = "mango-trunk" if trunk.provider == "mango" else f"trunk_{trunk.id}_{trunk.provider}"
                
                lines.extend([
                    "; Исходящие звонки",
                    "exten => _X.,1,NoOp(Исходящий звонок: ${EXTEN})",
                    "same => n,Set(CALLERID(num)=${CALLERID(num)})",
                    f"same => n,Dial(PJSIP/${{EXTEN}}@{trunk_name},60,tT)",
                    "same => n,Hangup()",
                    "",
                    ""
                ])
            
            # Контекст для входящих звонков с транка
            for trunk in company_trunks:
                lines.append(f"[from_trunk_{trunk.id}]")
                lines.append(f"; Входящие звонки для компании: {company.name}")
                
                # Находим телефонные номера для этого транка
                trunk_numbers = [pn for pn in phone_numbers if pn.trunk_id == trunk.id]
                
                if trunk_numbers:
                    for phone_number in trunk_numbers:
                        # Назначенный пользователь или первый доступный оператор
                        target_user = None
                        if phone_number.assigned_user_id:
                            target_user = next((u for u in company_users if u.id == phone_number.assigned_user_id), None)
                        
                        if not target_user and company_users:
                            target_user = company_users[0]  # Первый доступный оператор
                        
                        if target_user:
                            lines.extend([
                                f"exten => {phone_number.number},1,NoOp(Входящий на {phone_number.display_name or phone_number.number})",
                                f"same => n,Set(CALLERID(name)={phone_number.display_name or 'Client'})",
                                f"same => n,Set(COMPANY_ID={company.id})",
                                f"same => n,Set(TRUNK_ID={trunk.id})",
                            ])
                            
                            # AI агент (если включен)
                            if company.ai_enabled:
                                lines.extend([
                                    f"same => n,AGI(agi://{settings.asterisk_host}:{settings.api_port}/agi/call_start)",
                                ])
                            
                            lines.extend([
                                f"same => n,Dial(PJSIP/{target_user.sip_username},60,tT)",
                                "same => n,Hangup()",
                                ""
                            ])
                else:
                    # Если нет конкретных номеров, принимаем все входящие
                    if company_users:
                        target_user = company_users[0]
                        lines.extend([
                            "exten => _X.,1,NoOp(Входящий звонок)",
                            f"same => n,Set(COMPANY_ID={company.id})",
                            f"same => n,Set(TRUNK_ID={trunk.id})",
                        ])
                        
                        if company.ai_enabled:
                            lines.extend([
                                f"same => n,AGI(agi://{settings.asterisk_host}:{settings.api_port}/agi/call_start)",
                            ])
                        
                        lines.extend([
                            f"same => n,Dial(PJSIP/{target_user.sip_username},60,tT)",
                            "same => n,Hangup()",
                            ""
                        ])
                
                lines.append("")
        
        return "\n".join(lines)
    
    def _save_config(self, filepath: Path, content: str) -> None:
        """Сохраняет конфигурационный файл"""
        try:
            filepath.parent.mkdir(parents=True, exist_ok=True)
            filepath.write_text(content, encoding='utf-8')
            
            # Устанавливаем права 644 (rw-r--r--)
            filepath.chmod(0o644)
            
            logger.debug(f"📝 Сохранен: {filepath}")
        except Exception as e:
            logger.error(f"❌ Ошибка сохранения {filepath}: {e}")
            raise
    
    def reload_asterisk(self) -> dict:
        """
        Перезагружает конфигурацию Asterisk через Docker
        
        Returns:
            dict: Результат перезагрузки
        """
        try:
            # Выполняем команду reload в Asterisk CLI через docker exec
            result = subprocess.run(
                ["docker", "exec", "telephony-asterisk", "asterisk", "-rx", "core reload"],
                capture_output=True,
                text=True,
                timeout=10
            )
            
            if result.returncode == 0:
                logger.info("✅ Asterisk перезагружен успешно")
                return {
                    "status": "success",
                    "message": "Asterisk configuration reloaded",
                    "output": result.stdout.strip()
                }
            else:
                logger.error(f"❌ Ошибка перезагрузки Asterisk: {result.stderr}")
                return {
                    "status": "error",
                    "message": "Failed to reload Asterisk",
                    "error": result.stderr
                }
                
        except subprocess.TimeoutExpired:
            logger.error("❌ Timeout при перезагрузке Asterisk")
            return {
                "status": "error",
                "message": "Asterisk reload timeout"
            }
        except FileNotFoundError:
            logger.error("❌ Docker не найден. Убедитесь что docker доступен в PATH")
            return {
                "status": "error",
                "message": "Docker command not found. Make sure docker is available in PATH."
            }
        except Exception as e:
            logger.error(f"❌ Ошибка выполнения команды: {e}")
            return {
                "status": "error",
                "message": str(e)
            }


# Глобальный экземпляр генератора
config_generator = AsteriskConfigGenerator()
