"""Add is_active to Company and assigned_user_id to PhoneNumber

Revision ID: 35535c7db19f
Revises: 19ff207e58b9
Create Date: 2026-01-21 20:59:19.486504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35535c7db19f'
down_revision: Union[str, None] = '19ff207e58b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('phone_numbers', sa.Column('assigned_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'phone_numbers', 'users', ['assigned_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phone_numbers', type_='foreignkey')
    op.drop_column('phone_numbers', 'assigned_user_id')
    op.drop_column('companies', 'is_active')
    # ### end Alembic commands ###
